/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ILoot, ILootInterface } from "../ILoot";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "getHead",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ILoot__factory {
  static readonly abi = _abi;
  static createInterface(): ILootInterface {
    return new utils.Interface(_abi) as ILootInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ILoot {
    return new Contract(address, _abi, signerOrProvider) as ILoot;
  }
}
